/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all games */
        get: operations["listGames"];
        put?: never;
        /** @description Create a new game */
        post: operations["createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a game by ID */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/next-level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Validate current level on go to the next one */
        post: operations["nextLevel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/squares/{squareId}/update-position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update a square's position */
        post: operations["updateSquarePosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get game configuration */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    }[];
                };
            };
        };
    };
    createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        isDone: boolean;
                        levelIndex: number;
                        numberOfLevels: number;
                        board: {
                            numberOfColumns: number;
                            squares: ({
                                id: string;
                            } & ({
                                /** @enum {string} */
                                name: "pipe";
                                position: "pos-1" | "pos-2";
                            } | {
                                /** @enum {string} */
                                name: "corner";
                                position: "pos-1" | "pos-2" | "pos-3" | "pos-4";
                            } | {
                                /** @enum {string} */
                                name: "tee";
                                position: "pos-1" | "pos-2" | "pos-3" | "pos-4";
                            } | {
                                /** @enum {string} */
                                name: "cross";
                                /** @enum {string} */
                                position: "pos-1";
                            } | {
                                /** @enum {string} */
                                name: "sink";
                                position: "pos-1" | "pos-2" | "pos-3" | "pos-4";
                            } | {
                                /** @enum {string} */
                                name: "blank";
                                /** @enum {string} */
                                position: "pos-1";
                            }))[];
                        };
                        stats: {
                            startedAt: number;
                            finishedAt: number | null;
                            numberOfMoves: number;
                            numberOfWrongAttempts: number;
                        };
                    };
                };
            };
        };
    };
    nextLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSquarePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
                squareId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position: "pos-1" | "pos-2" | "pos-3" | "pos-4";
                };
            };
        };
        responses: {
            /** @description Default Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
